/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 08-Jul-2021 15:28:08
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 100
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * F:\MATLAB\R2018b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = 100;
const int16_T B[100] = {
        4,      1,      1,      0,     -1,     -3,     -7,    -12,    -19,
      -28,    -39,    -52,    -68,    -86,   -106,   -129,   -152,   -177,
     -202,   -226,   -249,   -269,   -285,   -296,   -300,   -296,   -283,
     -259,   -224,   -178,   -118,    -46,     39,    136,    244,    363,
      490,    624,    762,    902,   1041,   1177,   1306,   1427,   1536,
     1631,   1709,   1770,   1811,   1832,   1832,   1811,   1770,   1709,
     1631,   1536,   1427,   1306,   1177,   1041,    902,    762,    624,
      490,    363,    244,    136,     39,    -46,   -118,   -178,   -224,
     -259,   -283,   -296,   -300,   -296,   -285,   -269,   -249,   -226,
     -202,   -177,   -152,   -129,   -106,    -86,    -68,    -52,    -39,
      -28,    -19,    -12,     -7,     -3,     -1,      0,      1,      1,
        4
};
